version: '2'
services:
    web:
        build: .
        ports:
            - 8002:8002
        volumes:
            - .:/code
            - mole.io-deps:/code/node_modules
        links:
            - mongo
    mongo:
        image: mongo

volumes:
    mole.io-deps:
